WebUI/Controllers/BookController.cs

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using WebUI.Models;


namespace WebUI.Controllers
{
    public class BooksController : Controller
    {
        private IBookRepository repository;
        public int pageSize = 3;
        public BooksController(IBookRepository repo)
        {
            repository = repo;
        }
        public ViewResult List(string category, string author, int page = 1)
        {
            BooksListViewModel model = new BooksListViewModel();
            model.Books = repository.Books
                .Where(p => category == null || p.Category == category)
                .OrderBy(book => book.BookId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize);

            model.PagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = category == null ?
        repository.Books.Count() :
        repository.Books.Where(book => book.Category == category).Count()

            };
            model.CurrentCategory = category;
           
            //return JsonResult

            return View(model);
        }
    }
}

WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entities;
using Domain.Abstract;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repository;
        private IOrderProcessor orderProcessor;
        private IOrderRepository orderRepository;

        public CartController(IBookRepository repo, IOrderProcessor processor, IOrderRepository repo_ord)
        {
            repository = repo;
            orderProcessor = processor;
            orderRepository = repo_ord;
            Order myOrder = new Order();
            myOrder.OrderLines = new List<OrderLine>();

        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails, Order myOrder)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {/*
                foreach (CartLine line in cart.Lines)
                {
                    myOrder.OrderLines.Add(new OrderLine
                    {
                        //Order = myOrder,
                        Book = line.Book,
                        Quantity = line.Quantity
                    });
                }*/

                //orderRepository.SaveOrder(myOrder);
                orderProcessor.ProcessOrder(cart, shippingDetails);

                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }


        public RedirectToRouteResult AddToCart(Cart cart, int bookId, string returnUrl)
        {
            Book book = repository.Books
                .FirstOrDefault(g => g.BookId == bookId);

            if (book != null)
            {
                cart.AddItem(book, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int bookId, string returnUrl)
        {
            Book book = repository.Books
                .FirstOrDefault(g => g.BookId == bookId);

            if (book != null)
            {
                cart.RemoveLine(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;

        public NavController(IBookRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Books
                .Select(book => book.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }

    }
}

WebUI/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
namespace WebUI.Controllers
{
    public class SearchController : Controller
    {
        IBookRepository repository;
        // GET: Search
        public SearchController(IBookRepository repo)
        {
            repository = repo;
        }

        public ActionResult Index()
        {
            ViewBag.Title = "Поиск по автору";

            return View();
        }

        [HttpPost]
        public ActionResult BookSearch(string name)
        {
            
            var allbooks = repository.Books.Where(a => a.Author.Contains(name)).ToList();

            if (allbooks.Count <= 0)
            {
                return HttpNotFound();
            }

            return PartialView(allbooks);
            
        }
    }
}

WebUI/Views/Shared/BookSummary.cshtml
@model Domain.Entities.Book

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.BookId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Добавить в корзину" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <title></title>
</head>
<body>
   <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">КНИЖНЫЙ МАГАЗИН</a>
        <a></a>

        <a></a>
        @Html.Action("Summary", "Cart")
        <a></a>

       
        
    </div>

    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

WebUI/Views/Shared/_AdminLayoutAPI.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
     <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/Content/bootstrap.css" rel="stylesheet" />
    <link href="/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="/Content/ErrorStyles.css" rel="stylesheet" />

</head>

<body>
    <div>
       @Html.ActionLink("Домой", "List", "Books", null,
    new { @class = "btn btn-block btn-default btn-lg" })
    </div>
        



    


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebUI/Views/Shared/_Layot_Search.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layot_Search</title>


</head>
<body>
    <div> 
    </div>
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">КНИЖНЫЙ МАГАЗИН</a>

        
        <a></a>
        @Html.Action("Summary", "Cart")
        <a></a>
        <a></a>
        @using (Html.BeginForm("Index", "Search"))
        {
            <div class="navbar-right">

                @Html.Hidden("returnUrl", Request.Url.PathAndQuery),
                <input type="submit" class="btn btn-default navbar-btn" value="Поиск по автору" />
            </div>
        }



    </div>

    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
    
    
</body>
</html>